### PR TITLE
🚧 Bind actions

### LINKED ISSUE #27: Bind the continue button
Bind the continue button in the TE detail to send a continue action.

### PR DESCRIPTION
**Pull request by sofokli1**
Closes #27

### CODE REVIEW

**Comment by Odrakir** [comment]
Also, please, do test stuff on simulator or device before requesting review. Unit tests and previews are not cutting it.

**Comment by sofokli1** [comment]
If any action or api call is broken, it is unrelated to this PR based on the issues it is trying to close. Tapping continue should go back in the main log now

**Comment by Odrakir** [comment]
The problem with that is that there's no way to test this reliably. You either have to fix those issues in this PR or create issues and PRs to fix them before merging this one.

**Comment by sofokli1** [comment]
@Odrakir The continue action was broken and fixed here https://github.com/toggl/watchos-app/pull/85
This branch is updated and works, it is good for testing and merging

**Comment by Odrakir** [comment]
@sofokli1 Let's review and merge this one first: https://github.com/toggl/watchos-app/pull/87

**Pull request merged**
